<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ATM_Simulation</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ATM.Application\ATM.Application.csproj" />
    <ProjectReference Include="..\ATM.Domain\ATM.Domain.csproj" />
    <ProjectReference Include="..\ATM.Infrastructure\ATM.Infrastructure.csproj" />
  </ItemGroup>

</Project>
